---
language: node_js
node_js:
  # we recommend testing addons with the same minimum supported node version as Ember CLI
  # so that your addon works for all apps
  - "8"

sudo: false
dist: trusty

addons:
  chrome: stable

cache:
  directories:
    - $HOME/.npm

env:
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1

branches:
  only:
    - master
    # npm version tags
    - /^v\d+\.\d+\.\d+/

jobs:
  fail_fast: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-canary
    - env: EMBER_TRY_SCENARIO=ember-beta

  include:
    # runs linting and tests with current locked deps

    - stage: "Tests"
      name: "Tests"
      script:
        - npm run lint:hbs
        - npm run lint:js
        - npm test

    # we recommend new addons test the current and previous LTS
    # as well as latest stable release (bonus points to beta/canary)
    - stage: "Additional Tests"
      env: EMBER_TRY_SCENARIO=ember-release
    - env: EMBER_TRY_SCENARIO=ember-beta
    - env: EMBER_TRY_SCENARIO=ember-canary
    - env: EMBER_TRY_SCENARIO=ember-default-with-jquery

    - stage: "Deploy"
      name: "Deploy"
      if: (branch = master or tag is present) and type = push
      script:
      # travis's initial clone only configures our repo to use the master
      # branch, but we need to reconfigure it and re-fetch so we can interact
      # with the gh-pages branch.
       - git config --replace-all "remote.origin.fetch" "+refs/heads/*:refs/remotes/origin/*"
       - git fetch
       - git branch --track gh-pages origin/gh-pages
       # switch from HTTP to SSH and load our deploy key
       - git remote set-url origin git@github.com:cardstack/boxel
       - cat <<< "$DEPLOY_KEY" > ~/.ssh/boxel_key
       - ssh-add ~/.ssh/boxel_key
       - node_modules/.bin/ember deploy production --verbose

script:
  - node_modules/.bin/ember try:one $EMBER_TRY_SCENARIO
